### ISSUE TITLE
能不能支持到禁止鼠标滚轮事件，或者说可以配置，现在页面滑动到这个组件位置后容易进行缩放，同时移动端没有办法上下滑动

### ISSUE THREAD

**Issue by tryhank** [hululuuuuu/GlobeStream3D#11]

**Comment by hululuuuuu** [comment]
这个可以有，下个版本加上去。

**Comment by hululuuuuu** [comment]
新增了一个参数 config.enableZoom   禁止滚轮事件

**Comment by samaritanz** [comment]
移动端 不能左右滚动 这个有吗

**Comment by hululuuuuu** [comment]
@samaritanz   你希望的是 不能滚动这个功能，还是不能滚动这个问题呢？

**Comment by samaritanz** [comment]
不能滚动这个问题 现在移动端 好像滚动不了

**Comment by hululuuuuu** [comment]
移动端的支持这个项目确实没有考虑过，因为想到毕竟要吃性能，如果你那边确实没有滚动，我给你出个方案。 你可以在渲染容器上方定位一个 div 盖着容器。阻止容器的手势相关事件即可 @samaritanz
