### ISSUE TITLE
关于飞线尺寸的配置功能的实现

### ISSUE THREAD

**Issue by coldShan** [hululuuuuu/GlobeStream3D#12]
感谢这个项目，给我当前的工作带来了极大的便利。
我的项目中需要点击地球的飞线展示数据，默认的飞线太细了不好点击，文档中没看到线条尺寸的配置，fork了项目尝试自己实现。
看文档发现[linewidth](https://threejs.org/docs/index.html#api/en/materials/LineBasicMaterial.linewidth)属性似乎只能是1。之后在官方示例中找到了这个[webgl_lines_fat](https://threejs.org/examples/?q=fat#webgl_lines_fat)，可以实现粗线条。
我基于这个示例改了源码，实现了线条尺寸的配置[commit:add size config to pathLine and flyLine](https://github.com/coldShan/earth-flyLine/commit/ba9d45055d8b4b00f81a80b20efa0913be9cba72)。过程中我发现[/lib/interface.ts](https://github.com/JavaScriptam/earth-flyLine/blob/main/src/lib/interface.ts)中有声明`size`属性，就直接使用了这个字段。
![粗线条](https://github.com/JavaScriptam/earth-flyLine/assets/20255358/1560e0d7-9ae8-4708-9649-00267a50ea89)

不知道大佬有没有对`size`字段规划更好的实现方案，这个功能必要的话我可以提个pr。

另外，使用文档里的[鼠标交互事件](https://javascriptam.github.io/earth-flyline-docs/reference/event/)点击线条返回的`userData `好像总是`{}`，我临时改了下这个功能，点击飞线返回了`...rest`。

**Comment by hululuuuuu** [comment]
@coldShan  没问题的，万分感谢。关于线条的 pr。另外点击 userData 没有返回当前数据吗，如果没有返回的话，我晚上追一下代码再给你答复。

**Comment by hululuuuuu** [comment]
@coldShan  这个项目我只是开个头，是我的项目也是你们的项目，有想法随时沟通。再次感谢你提供的帮助 😄

**Comment by hululuuuuu** [comment]
还有一个点，本来是想做两根线，一根在视图上显示，一根是透明的，但是会比较粗，这样样式可能会更美观，你这个方案先提pr 做一个过渡。

**Comment by hululuuuuu** [comment]
@coldShan 关于点击 pathline 没有返回 userData 的问题 已修复 [v.1.3.1](https://github.com/JavaScriptam/earth-flyLine/commit/9269834a6af00dca1cf6c4e93b20524bbc0dd185).请升级版本

**Comment by coldShan** [comment]
@JavaScriptam  谢谢，看到了，我把之前我改的userData就删掉了，已提交pr，只添加了3D线条的size配置

**Comment by hululuuuuu** [comment]
@coldShan  npm 已更新到 v1.3.2

**Comment by hululuuuuu** [comment]
@coldShan  你好由于一些特殊的原因 项目改名了 ，而且项目 markdown 文档地址暂时隐藏。等过年之后我会看情况再更改回来，npm 包没有变。

**Comment by coldShan** [comment]
@JavaScriptam 好的，谢谢提醒
