### ISSUE TITLE
地球视角下，球体控制有问题

### ISSUE THREAD

**Issue by liuwo23** [hululuuuuu/GlobeStream3D#14]
地球视角下，球体控制有问题

有时候左键控制视角，点击左键滑动，球体没有转动。

浏览器：chrome， edge

猜测：TransformControls的事件有冲突吧

**Comment by hululuuuuu** [comment]
你猜到了是控制器，不能说有冲突。是这个控制器的手柄大小的问题，导致鼠标可能没放到控制器上，导致的交互不生效，所以我在想自己手搓一个转换器得了，不用TransformControls。可是最近项目太多啦，难以腾出手来。 @liuwo23

**Comment by hululuuuuu** [comment]
项目现有的一些瑕疵我都记录下来了。希望24 年第一季度能有时间结束掉项目的一些痛点，并增加一些功能

**Comment by liuwo23** [comment]
> 项目现有的一些瑕疵我都记录下来了。希望24 年第一季度能有时间结束掉项目的一些痛点，并增加一些功能

**Comment by liuwo23** [comment]
> 你猜到了是控制器，不能说有冲突。是这个控制器的手柄大小的问题，导致鼠标可能没放到控制器上，导致的交互不生效，所以我在想自己手搓一个转换器得了，不用TransformControls。可是最近项目太多啦，难以腾出手来。 @liuwo23

看了下代码，项目中的transformcontrols 只设置y轴也就是赤道区域(showy = true)，能触发旋转。这个控制器不太适合这个项目，确实需要重新写一下。

**Comment by liuwo23** [comment]
> 项目现有的一些瑕疵我都记录下来了。希望24 年第一季度能有时间结束掉项目的一些痛点，并增加一些功能

期待

**Comment by hululuuuuu** [comment]
@liuwo23  放心，这个项目既然都做了这么多了 肯定要好好做下去了，有始有终，换是一定要换的，已经有思路了，就差凑出来点时间写代码了。等优化好了 会通知你

**Comment by hululuuuuu** [comment]
@liuwo23 可以看下最新版。写了个控制器，不过目前鼠标事件是通过renderer.domElement捕获的，后续加入raycaster 做更严密的判断

**Comment by hululuuuuu** [comment]
文档在这里http://localhost:3001/reference/property/#configearth  也可以在文档首页体验
