### ISSUE TITLE
最新边界墙似乎不支持混合策略

### ISSUE THREAD

**Issue by AdamZHC** [hululuuuuu/GlobeStream3D#16]
1.3.5和1.3.7相同的配置，混合注册的地图的国家底色无法显示

**Comment by hululuuuuu** [comment]
感谢最新反馈，实在是忙晕了工作，没测试到位，等我看看兼容一下

**Comment by hululuuuuu** [comment]
@AdamZHC  你好 ，关于混合策略，我是这样理解的
混合策略的目的是希望关于部分地图色块复杂定制化（目前组件做不到的复杂样式），比如说希望给某个国家进行设置一个复杂的样式，其他的地区样式依旧采用 js 绘制。

我来举个例子，我希望加拿大这个国家有独立的贴图样式，而其他的区域照旧。
那么想实现这种效果有两种方式
1、应该是在注册地图前，处理一次地图数据，把加拿大相关数据给排除掉再进行地图注册。组件就不会绘制相关区域，这样贴图自然而然就显示出来了
2、我们不想处理地图文件，那么我们可以通过设置 config.regions.Canada.show 为 false，组件同样不会渲染该片区域。

所以针对这里的逻辑，我又进一步进行了处理，也修复了上次 pr 里的一点小问题。

或者是关于该功能，您有什么更好的思路。期待您的回复～

**Comment by hululuuuuu** [comment]
@AdamZHC  本地测试了一下  目前这样设置是没问题的
<img width="393" alt="image" src="https://github.com/hululuuuuu/GlobeStream3D/assets/25917806/904c8914-f9d4-4d9a-a0c1-ae0bd73c141e">

**Comment by hululuuuuu** [comment]
> @AdamZHC 本地测试了一下 目前这样设置是没问题的 <img alt="image" width="393" src="https://private-user-images.githubusercontent.com/25917806/311637991-904c8914-f9d4-4d9a-a0c1-ae0bd73c141e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNDcxNjksIm5iZiI6MTcxMDE0Njg2OSwicGF0aCI6Ii8yNTkxNzgwNi8zMTE2Mzc5OTEtOTA0Yzg5MTQtZjlkNC00ZDlhLWEwYzEtYWUwYmQ3M2MxNDFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDA4NDc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmNmIwZTI3ZDNkYTBhZjAzZTNlMzRiYTFmODNkOWFkMTNhYzYzNWM3OTFiMDUxMzI2MWY5MDc2ZDhkZDU4ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kcheVrRhnIitz2goxUcWULI7UBaTx0mz99zHF4ViPPs">

此配置是 1.3.8 版本 麻烦升级到 1.3.8 版本

**Comment by AdamZHC** [comment]
明白您的意思了！

**Comment by hululuuuuu** [comment]
@AdamZHC  混合策略是个非常好的想法，感谢参与，目前最新版 1.3.9 。
