### ISSUE TITLE
球体空间移动的问题

### ISSUE THREAD

**Issue by seek9527** [hululuuuuu/GlobeStream3D#17]
目前想加入一些在三维空间球体运动的效果，想基于TWEEN实现，但是获取不到球体对象，有没有好的方法

**Comment by hululuuuuu** [comment]
const chartInstance = chart.init()
 chartInstance.mainContainer 里有相关球体 group 等。
 具体可以打印一下看看。 
 基本上大部分都暴露出去了

**Comment by hululuuuuu** [comment]
基于你目前的描述，我不知道还需要提供哪些返回字段，可以更详细描述一下

**Comment by seek9527** [comment]
好的，感谢，我试试

**Comment by CrazyMcdull** [comment]
Mesh网格有暴露出来吗

**Comment by hululuuuuu** [comment]
@CrazyMcdull   mesh 本身就在 group 里面，如果针对 mesh 单独暴露，那就太多了。从 group 里面找需要的数据。

**Comment by seek9527** [comment]
使用init后，默认会创建相机吗？如何默认创建PerspectiveCamera这种相机，而不是普通相机呢？（需求是只有PerspectiveCamera相机支持拉远视距后，整个空间会缩放）

**Comment by hululuuuuu** [comment]
这里可以功能拓展一下，下个版本加上可配置指定相机，其实接口已经预留了，没深入去做

**Comment by seek9527** [comment]
飞线的路径线PathStyle可以透明或者不展示吗，目前没找到相关设置

**Comment by hululuuuuu** [comment]
今天有事，明天我看看，如果不支持的话我下个版本新增该功能

**Comment by hululuuuuu** [comment]
@seek9527  已更新 pathStyle.show
