### ISSUE TITLE
手机端不能操作球体模型

### ISSUE THREAD

**Issue by Vvaraz** [hululuuuuu/GlobeStream3D#18]
你好，我的项目用到了这个3D模型，现在需要适配手机端，但是发现手机端不能滚动，当点模型的时候模型的自转也停止了，有办法解决吗

**Comment by hululuuuuu** [comment]
因为此项目使用的是鼠标事件，暂时没有对手机交互优化的计划，抱歉。

**Comment by hululuuuuu** [comment]
关于自转的问题，看一遍文档，配置一下不会因为点击停止。

**Comment by hululuuuuu** [comment]
stopRotateByHover 这个配置一下 为 false

**Comment by Vvaraz** [comment]
我的问题都是在手机端的，看来是不兼容移动端交互的原因，不过我的问题已经解决。感谢回复！
