### ISSUE TITLE
节点配置颜色或者纹理贴图都会变成白色，颜色、贴图无效

### ISSUE THREAD

**Issue by Vvaraz** [hululuuuuu/GlobeStream3D#19]
我按照文档的配置给节点修改颜色或者贴图，都不生效
```typescript
import point_red from "./assets/point_red.png";
import earth_map from "./assets/earthmap.png";

var arr = [{
    from: {
        lon: 32.5825,
        lat: 0.3476,
        style: {
           scatterStyle: {
             color: "#246CF9",
             customFigure: {
               texture: point_red,
       },
    }
    to: {
        lon: 6.7273,
        lat: 0.1864,
        style: {
           scatterStyle: {
           color: "#246CF9",
           customFigure: {
             texture: point_red,
        },
    }
}]
const chart = earthFlyLine.init({
      dom: earthRef.current,
      rotateSpeed: 0.003,
      stopRotateByHover: false,
      config: {
        flyLineStyle: {
          duration: 5000,
        },
        texture: {
          path: earth_map,
          mixed: false,
        },
        bgStyle: {
          color: "#0e0c15",
        },
        spriteStyle: {
          color: "#272335",
          show: true,
        },
      },
});
chart.addData("flyLine", arr)
``` 
最终结果节点都是白色的，不知道是我配置不对还是bug
![image](https://github.com/hululuuuuu/GlobeStream3D/assets/73987251/727ad56b-7ebd-4f58-8a8b-7213820deb40)

**Comment by hululuuuuu** [comment]
使用的是哪个版本？ 我使用了你的配置 ，使用地球贴图目前是没问题的，可能问题出在图片上，如果要更深一步排查，希望给我一个可复现的仓库地址。

**Comment by Vvaraz** [comment]
版本1.3.9
不用贴图，我改变color也不生效，也是白色
这些就是我基本所有的代码了，剩下的是css样式

**Comment by hululuuuuu** [comment]
如果不方便给复现代码的话，可以参考本项目的 app.vue 里面的代码 
<img width="1134" alt="image" src="https://github.com/hululuuuuu/GlobeStream3D/assets/25917806/09153dce-12e6-4f08-a586-9fd05d6c6f1f">
并且使用本项目 src/image/triangel.png 或者 src/image/triangel.svg 
<img width="415" alt="image" src="https://github.com/hululuuuuu/GlobeStream3D/assets/25917806/65de7aa1-55e9-49bf-a938-9bfa712f0578">
看看是否生效，如果不生效可能是代码配置问题，如果生效，可能就是图片本身的问题。

**Comment by Vvaraz** [comment]
好的谢谢😃。是配置错了，我把配置放在style.scatterStyle下了，因为我看文档是说涟漪的配置是config.scatterStyle字段

**Comment by hululuuuuu** [comment]
配置好了就行。
