### ISSUE TITLE
按照文档使用贴图会报错

### ISSUE THREAD

**Issue by 970319330** [hululuuuuu/GlobeStream3D#20]
chart.value = earthFlyLine.init({
    mode:'3d',
    dom,
    // map: "world",
    config:{
      texture:imageUrl,
      stopRotateByHover:false,
      bgStyle:{
        color: "#fff",
        opacity:0.1, 
      },
      R:80,
      mapStyle:{
        areaColor: "#f1f2f3", //区域颜色
        lineColor: "#ccc",//边界线颜色
      },
      hoverRegionStyle:{
        "areaColor": "#333",
        "opacity": 1,
        "show": true
      },
      enableZoom:false
    }
    
  });

**Comment by g327513353** [comment]
老哥怎么解决的

**Comment by hululuuuuu** [comment]
<img width="908" alt="image" src="https://github.com/hululuuuuu/GlobeStream3D/assets/25917806/93b0c4ec-dd7c-481e-9941-ec88ef323876">
是 config.texture.path 
具体参考这里
https://globestream3d.netlify.app/reference/property/#configtexture-%E5%8F%AA%E6%94%AF%E6%8C%81-3d-%E6%A8%A1%E5%BC%8F

**Comment by g327513353** [comment]
感谢！

**Comment by hyzxy9** [comment]
请问如何显示国家名称呢

**Comment by hululuuuuu** [comment]
这个版本暂不支持，不过正在考虑加入此功能，目前正在开发柱状图功能，可能要等一等了
