### ISSUE TITLE
手机端卡顿问题

### ISSUE THREAD

**Issue by lan-he** [hululuuuuu/GlobeStream3D#21]
PC端非常好，也完美符合需求，只是手机浏览几打开就会巨卡无比，并且无法滑动旋转，就连打开项目官网的地球仪也是一样，求作者大大解决，十分感谢🙏

**Comment by hululuuuuu** [comment]
您好 朋友很开心您对本项目 pc 端的认可，但是很抱歉目前没有对手机端进行适配的打算（因为工作比较忙，而且目前针对手机优化可能要处理相对多的代码，主要在手指交互这块儿），如果您觉得手机端卡顿，您可以使用贴图的模式去渲染地球组件，这样可以节省很多系统资源去计算点位，使用贴图对于性能会有较大改善。
