### ISSUE TITLE
怎么在飞线上，hover时展示一个气泡框 展示一些自定义的内容呢

### ISSUE THREAD

**Issue by qiyx2019** [hululuuuuu/GlobeStream3D#23]
怎么在飞线上hover时展示一个气泡框 展示一些自定义的内容呢

**Comment by hululuuuuu** [comment]
自定义事件，通过你的外层业务代码实现，最无脑的做法就是 根据 hover 事件去做，然后自己手动写一个 html 气泡框，判断鼠标的位置，定位好气泡框，把要展示的内容放进去。
