### ISSUE TITLE
有什么方法可以在飞线生成的时候展示一个气泡框吗？

### ISSUE THREAD

**Issue by qiyx2019** [hululuuuuu/GlobeStream3D#24]
有什么方法可以在飞线生成的时候展示一个气泡框吗？

**Comment by hululuuuuu** [comment]
这些都是通过你本身业务代码实现的，生成飞线是需要调用 setdata 方法的， 调用 setdata 之后，自己实现气泡框逻辑，在和 ui 沟通后展示到希望展示的位置。如果希望展示到飞线旁边，需要进行复杂的计算，根据当前经纬度根据自己业务实际需求计算出需要展示的位置。

**Comment by hululuuuuu** [comment]
下个版本考虑开发一个 tooltip 气泡功能。

**Comment by qiyx2019** [comment]
好的 感谢
