### ISSUE TITLE
如何显示国家名称呢

### ISSUE THREAD

**Issue by hyzxy9** [hululuuuuu/GlobeStream3D#26]
请问如何显示国家名称

**Comment by hululuuuuu** [comment]
这个版本暂不支持，不过正在考虑加入此功能，目前正在开发柱状图功能，可能要等一等了。

**Comment by hululuuuuu** [comment]
@hyzxy9  刚更新了 1.5.3 版本。 下个迭代加入显示国家名称的需求

**Comment by hyzxy9** [comment]
好的感谢🙏

**Comment by hululuuuuu** [comment]
@hyzxy9  已更新 textMark 字段。支持文字模块，可以把你想展示的国家名称手动配置进去 。  国家相关经纬度等信息 在本项目 src/map 下。
