### ISSUE TITLE
通过设置经纬度旋转到某一个国家正上方

### ISSUE THREAD

**Issue by Junezm** [hululuuuuu/GlobeStream3D#27]
大佬，请问下是否支持通过设置经纬度，摄像头旋转到当前经纬度的正上方，也就是通过经纬度值转换成摄像头坐标，达到旋转到某一个国家或者城市？

**Comment by hululuuuuu** [comment]
那必须是可以的，  
new 实例化之后 
chartInstance.camera.position.set(0,  0 500);（地球中心位置 0,0,0 ）
chartInstance.camera.lookAt(0, 0, 0);
通过实例里面的 camera 调整。 
后续我会做一个调试模式 可以把相机具象化出来，方便调整角度

**Comment by hululuuuuu** [comment]
@Junezm 设置经纬度的话还不行，不过可以做，你可以按照我刚刚给你的思路先满足目前的需求，等我下个迭代把这个功能做上去

**Comment by Junezm** [comment]
好的，谢谢大佬，我试试

> @Junezm 设置经纬度的话还不行，不过可以做，你可以按照我刚刚给你的思路先满足目前的需求，等我下个迭代把这个功能做上去

好的，谢谢大佬，我试试哈
