### ISSUE TITLE
地球如何自适应屏幕，有没配置示例

### ISSUE THREAD

**Issue by jackchen0120** [hululuuuuu/GlobeStream3D#29]
地球如何自适应屏幕，有没配置示例

**Comment by hululuuuuu** [comment]
地球的大小基于 半径参数：R ，同时依赖于外部容器的宽高。

**Comment by hululuuuuu** [comment]
没有自适应这个功能。

**Comment by jackchen0120** [comment]
后续版本迭代会加上么

**Comment by hululuuuuu** [comment]
> 后续版本迭代会加上么

这个功能在我看来是不必要的，完全通过业务层可以解决的，如果我加入这个逻辑在组件内部处理自适应，可能反而对另一部分喜欢自己调整大小的开发者带来一部分不便捷。所以这个功能目前不考虑加入，如果后续有更多使用者反馈了该问题，我会认真考虑这个功能，最后真心感谢你所提的这个建议。
