### ISSUE TITLE
3D地球加入贴图功能，通过地图图片替换json地图文件

### ISSUE THREAD

**Issue by gooohy** [hululuuuuu/GlobeStream3D#3]
现有功能满足我的需求，但是需要引入地图json文件，希望新增贴图的功能，直接通过图片代替json文件

**Comment by hululuuuuu** [comment]
下个版本支持，

**Comment by hululuuuuu** [comment]
![image](https://github.com/JavaScriptam/earth-flyLine/assets/25917806/fdcbf2da-fd68-4e02-80ee-d7240ac02a39)
当然 你也可以参考src/App.vue

**Comment by tryhank** [comment]
贴图后左下角会存在一部分阴影,可以通过配置取消阴影么,我看通过json生成的是没有阴影的

**Comment by hululuuuuu** [comment]
@tryhank  方便截个图吗？标记一下 我看看哪里的阴影

**Comment by tryhank** [comment]
<img width="470" alt="image" src="https://github.com/JavaScriptam/earth-flyLine/assets/59812833/560a7d58-8b2b-4838-a20b-2eacecc21c19">
![image](https://github.com/JavaScriptam/earth-flyLine/assets/59812833/f6753d4b-f26a-4d7b-9084-31b36ad8415b)
我把创建材料修改后就没有阴影了,不知道是否有其他影响

**Comment by hululuuuuu** [comment]
这个不是 bug， 这是因为地球使用了反光材质造成的。近期等手头项目做完我会增加一个配置项，可以通过配置取消这类效果。

**Comment by hululuuuuu** [comment]
@tryhank   可能下个月初会进行这个功能的迭代，因为最近项目比较多。

**Comment by hululuuuuu** [comment]
@tryhank   新增了 材质配置https://earth-flyline-docs.vercel.app/changelog/log/  查看文档即可。
