### ISSUE TITLE
文档的options.stopRotateByHover写错了，这个属性实际上实在config下的

### ISSUE THREAD

**Issue by geogreyyyy** [hululuuuuu/GlobeStream3D#30]
![image](https://github.com/user-attachments/assets/86378476-664f-4f82-88b3-5594199ca2a3)

**Comment by hululuuuuu** [comment]
好的 收到。已经更新了
<img width="1216" alt="image" src="https://github.com/user-attachments/assets/532e4270-5824-420a-826b-19ad9d502456">

感谢反馈
