### ISSUE TITLE
光柱 设置粗细

### ISSUE THREAD

**Issue by vcfeelings** [hululuuuuu/GlobeStream3D#31]
我想给光柱 设置半径 如何实现 目前只看到了 有opacity和color参数

**Comment by hululuuuuu** [comment]
OK，不过要晚点安排了。年前了公司业务太多，洗净忙炸了。我看看下个月能不能抽出时间更新一版

**Comment by hululuuuuu** [comment]
@vcfeelings  更新了新版本 支持设置 width 和 height 控制粗细。
