### ISSUE TITLE
textMark设置没有用是为什么

### ISSUE THREAD

**Issue by xu-zhi-heng** [hululuuuuu/GlobeStream3D#32]
textMark: {
            //公共样式配置
            style: {
              fontSize: 20,
              color: "red"
            },
            data: [
              {
                position: [116.46, 39.92],
                text: "北京",
                //定制化样式配置
                style: {
                  fontSize: 22,
                  color: "red"
                }
              }
            ]
          }

**Comment by hululuuuuu** [comment]
有升级吗？

**Comment by hululuuuuu** [comment]
抱歉文档写错了  。
  textMark: {
          //公共样式配置
          style: {
            fontSize: 20,
            color: "red",
          },
          data: [
            {
              position: {
                lon: 116.405285,
                lat: 39.904989,
              },
              text: "北京",
              //定制化样式配置
              style: {
                fontSize: 22,
                color: "red",
              },
            },
          ],
        },
