### ISSUE TITLE
地球一开始加载的时候如何设置地球面向的位置，比如一开始就让中国正面显示

### ISSUE THREAD

**Issue by xu-zhi-heng** [hululuuuuu/GlobeStream3D#33]

**Comment by hululuuuuu** [comment]
https://github.com/hululuuuuu/GlobeStream3D/issues/27  可以参考一下这个思路。通过调整相机视角来侧面满足需求。

**Comment by xu-zhi-heng** [comment]
> #27 可以参考一下这个思路。通过调整相机视角来侧面满足需求。
这个是可以通过您现在的哪些参数来配置，如果现在的配置满足不了话，相机视角是哪个技术里面的three.js吗

**Comment by hululuuuuu** [comment]
这个是 threejs 带的相机。本项目是基于 threejs 开发的，所以可以调整一下相机的位置  ，来达成你需要的效果。调整 x y z 三个参数即可
