### ISSUE TITLE
文字现在的配置只有文档那些吗，有没有类似echarts中label的显示方式，麻烦了

### ISSUE THREAD

**Issue by xu-zhi-heng** [hululuuuuu/GlobeStream3D#34]

**Comment by hululuuuuu** [comment]
目前只有这些 颜色和大小， 你还希望哪些显示 可以提给我。我来评估一下. 需要背景色等之类的配置吗？

**Comment by xu-zhi-heng** [comment]
> 目前只有这些 颜色和大小， 你还希望哪些显示 可以提给我。我来评估一下. 需要背景色等之类的配置吗？

我看他自己是直接和点贴在一起的，类似于当地球旋转的时候，有些特定的点坐标的周围（自己设置position）这样，可以设置文字内容，包括动画之类的，可以参考echarts中的

**Comment by hululuuuuu** [comment]
这个组件和 echarts 设计思路不一样，我这边希望提供给开发者的是纯功能，没有更多的封装，好处就是更灵活，自定义性更强，至于你说的是 echarts 的效果其实不是技术上的问题，是设计思路不同而已。 我的思路就是 需要放什么文字，在哪个位置就自己设置即可。后续还会增加动态设置文案的位置。

**Comment by xu-zhi-heng** [comment]
> 这个组件和 echarts 设计思路不一样，我这边希望提供给开发者的是纯功能，没有更多的封装，好处就是更灵活，自定义性更强，至于你说的是 echarts 的效果其实不是技术上的问题，是设计思路不同而已。 我的思路就是 需要放什么文字，在哪个位置就自己设置即可。后续还会增加动态设置文案的位置。

好的，感谢
