### ISSUE TITLE
文档上能加个 vue3中使用的demo吗 

### ISSUE THREAD

**Issue by weiShaoY** [hululuuuuu/GlobeStream3D#35]
<script lang="ts" setup>
import earthFlyLine from 'earth-flyline' // 确保库名和导入路径正确

import { onMounted, ref } from 'vue'

const imageUrl = './image/bumpImage.jpeg'

const container = ref<HTMLDivElement | null>(null)

onMounted(() => {
  if (container.value) {
    earthFlyLine.init({
      dom: container.value,
      config: {
        texture: {
          path: imageUrl,
          mixed: false,
        },

        // 根据earth-flyline的文档，可能需要添加其他配置
      },
    })
  }
})
</script>

<template>
  <div
    ref="container"
    class="h-[400px] w-[400px] overflow-hidden"
  />
</template>
我这么写 贴图显示不出来

**Comment by hululuuuuu** [comment]
这个项目本身使用的就是 vue3  你可以 clone 下来试一试，你这个配置我本地试了一下是没问题的， 看下版本是不是最新的？ 还有图片 url 建议 import 引入  
例如：
import imageUrl from "./image/bumpImage.jpeg";

**Comment by hululuuuuu** [comment]
const imageUrl = './image/bumpImage.jpeg'   你这样的写法路径会有问题的。改成 import 引入就可以了

**Comment by weiShaoY** [comment]
> const imageUrl = './image/bumpImage.jpeg' 你这样的写法路径会有问题的。改成 import 引入就可以了

好的,谢谢老哥, 对了想问下,有群吗

**Comment by hululuuuuu** [comment]
没群的哟。在使用上的问题和一些建议可以随时 issue 里反馈
