### ISSUE TITLE
config.texture.mixed = true，时，可以把地图颜色设置成透明吗

### ISSUE THREAD

**Issue by smile6611** [hululuuuuu/GlobeStream3D#40]

**Comment by hululuuuuu** [comment]
参考文档，颜色rgba 可以把 alpha 设置为 0

**Comment by smile6611** [comment]
设成rgba，报错index.es.js:5572 THREE.Color: Unknown color model rbga(48, 148, 192, 0)
颜色也没有变成透明

**Comment by hululuuuuu** [comment]
把你的代码贴出来。

**Comment by smile6611** [comment]
this.mapOption = {
        dom: document.querySelector('#' + this.id),
        map: 'world',
        autoRotate: true,
        light: 'AmbientLight',
        config: {
          R: this.R,
          bgStyle: {
            opacity: 0,
          },
          texture: {
            path: require('./earth.jpg'),
            mixed: true,
          },
          earth: {
            color: '#fff',
          },
          mapStyle: {
            areaColor: 'rbga(48, 148, 192, 0)',
            lineColor: '#2db5e7',
          },
          spriteStyle: {
            color: '#8dddee',
          },
          pathStyle: {
            color: '#cd79ff',
          },
          flyLineStyle: {
            color: '#cd79ff',
          },
          // scatterStyle: {
          //   color: '#f47b21',
          //   size: 10,
          // },
          hoverRegionStyle: {
            areaColor: '#cd79ff',
          },
          regions: {},
          textMark: {
            //公共样式配置
            style: {
              fontSize: 50,
              color: '#fff',
            },
            data: [],
          },
        },
      }

**Comment by smile6611** [comment]
这样设置有问题吗

**Comment by hululuuuuu** [comment]
我明白你说的意思了，之前没太理解。 透明度上个版本去掉了。因为觉得透明这个是伪需求，实在不知道使用场景在哪里

**Comment by smile6611** [comment]
现在是不支持 了是吗

**Comment by ultraman-agul** [comment]
我也有球体透明的需求，怎么处理好
