### ISSUE TITLE
鼠标拖拽点住，地球转动不停，一直抽搐

### ISSUE THREAD

**Issue by liutingfenga** [hululuuuuu/GlobeStream3D#5]

**Comment by hululuuuuu** [comment]
好的 。下个版本修复

**Comment by hululuuuuu** [comment]
@liutingfenga  更新了一个功能 , 新增参数 options.config.stopRotateByHover。这本来是后面规划要做的。 鼠标hover之后地球会停止旋转。 详情请参考[文档](https://javascriptam.github.io/earth-flyline-docs/reference/property/#optionsstoprotatebyhover)
