### ISSUE TITLE
options.bgColor参数的问题

### ISSUE THREAD

**Issue by SendohDUNK** [hululuuuuu/GlobeStream3D#6]
感谢提供如此方便的包！
但在设置options.bgColor参数时，发现运行后背景颜色始终为默认值，其他参数则能正常设置。是因为文档中参数名称错误了吗？
感谢！

**Comment by hululuuuuu** [comment]
我排查一下看看 @SendohDUNK

**Comment by hululuuuuu** [comment]
@SendohDUNK  这个地方文档写错了，应该是 options.config.bgColor  感谢您的反馈，我修改一下文档
