### ISSUE TITLE
chart.remove 方法 无论是通过 ids 还是 removeAll 都无法清除所有数据是什么原因呢

### ISSUE THREAD

**Issue by tryhank** [hululuuuuu/GlobeStream3D#7]

**Comment by hululuuuuu** [comment]
提供一下代码呢  比如说提供一下 chart.add 。我这边本地测试一下 @tryhank

**Comment by hululuuuuu** [comment]
目前本地复现了这个问题。我来排查一下。

**Comment by tryhank** [comment]
感谢回复
我就是使用函数随机生成十个point,添加后正常展示,然后清除的时候会随机清除.

**Comment by hululuuuuu** [comment]
已在 1.2.4 版本修复 可以升级一下。  issue 是项目前进的动力，有问题我会在第一时间修复 以及响应
