### ISSUE TITLE
鼠标点击事件报错

### ISSUE THREAD

**Issue by LeeLure** [hululuuuuu/GlobeStream3D#8]
相关版本：vue:3.3.0 , vite:3.2.3 , earth-flyline:^1.2.4
在 onMounted 里注册鼠标点击事件，点击时报错只读，请问是什么原因。
![image](https://github.com/JavaScriptam/earth-flyLine/assets/107562467/92f5116b-5f5a-4349-b180-f03bc214c88e)
使用的JSON数据为该项目的world.json   https://github.com/337547038/echartMap/blob/master/allMap/world.json

**Comment by hululuuuuu** [comment]
好的，我这边看下

**Comment by LeeLure** [comment]
还有一个问题是鼠标 hover 时位置不对。

**Comment by LeeLure** [comment]
![image](https://github.com/JavaScriptam/earth-flyLine/assets/107562467/9def0ea3-f19f-4789-b73d-9a5b711278dc)
红色箭头是鼠标当时所在位置，绿色箭头指向的是高亮的区域

**Comment by hululuuuuu** [comment]
@LeeLure   首先 const chart = ref(null)  

修改为  
import { shallowRef } from "vue";
let chartInstance1 = shallowRef(null);

**Comment by hululuuuuu** [comment]
至于 hover 的位置不对 这个因素有很多。代码层面是通过射线投射转换坐标去做的。

目前遇到的最多的是
1、用户的浏览器缩放设置或设备的像素比，可能会影响鼠标坐标的准确性。
2、在某个复杂 dom 元素 并且设置了 scale等 css 导致的
解决思路：1、 调整一下设备分辨率 有没有进行缩放 。
2、提供最小复现代码给到我，我这边多个设备运行 协助排查，看一下是否出现相同问题，如果这边多个设备跑起来不存在此问题 可能要再排查你那边设备本身分辨率相关问题

**Comment by hululuuuuu** [comment]
@LeeLure   目前我们这边遇到的所有 大屏项目问题最多的在父元素 css 上。 父元素设置了 position relative 导致的。看下有没有。我这边只能帮你猜了 ，最好提供一下可复现代码

**Comment by hululuuuuu** [comment]
@LeeLure 下个版本优化一下鼠标交互事件的逻辑计算方式，防止被父元素影响

**Comment by hululuuuuu** [comment]
@LeeLure  试一下 最新版本 1.2.5。我盲猜做了一波优化
