### ISSUE TITLE
飞线效果是否可以贴地

### ISSUE THREAD

**Issue by paddingH** [hululuuuuu/GlobeStream3D#9]
飞线样式是否可以贴地

**Comment by hululuuuuu** [comment]
在技术上必须是可以的。而且相对是简单的。  但是他在概念上不属于 飞线，而是路线。
我在规划下一个版本的路线模块的开发。 目前版本不支持 贴地。下月准备开始这些功能的开发功能。

**Comment by paddingH** [comment]
大神，目前有可以自己扩展实现路线的建议吗？比较紧急

**Comment by hululuuuuu** [comment]
扩展路线？具体说说，我看看怎么个事儿

**Comment by hululuuuuu** [comment]
你可以组织一下你的需求和想法。然后我评估一下。 想要什么样的功能，以及达到什么样的效果

**Comment by paddingH** [comment]
在您这个组件基础上自己去做路线的开发

**Comment by hululuuuuu** [comment]
@paddingH    如果是自己去做开发的话 ，要学习 threejs，如果你会 threejs 的话在我这个组件的基础上去做 其实是很简单的。，如果你不会 threejs 那不太现实。你这边如果很急的话 我这边可以开始做相关开发，毕竟这个功能是早晚要上的。今天下午我先设计一下代码。明天给你答复看看短期能不能做完（因为手头比较忙，项目较多），请见谅。

**Comment by hululuuuuu** [comment]
@paddingH   今天构思了几个小时，想了不同的方案，我先收回 路线图相对简单这句话，路线图如果在 2D 平面上是相对简单的，如果是两种地图同时支持 是比较麻烦的，明天我会写个 demo 试一下我的思路。如果明天没问题，几天内就可以发布了。

**Comment by hululuuuuu** [comment]
新版本已发布 请升级致1.2.6 
具体查看文档示例  [roadStyle](https://earth-flyline-docs.vercel.app/reference/property/#configroadstyle) 以及使用方法[addData](https://earth-flyline-docs.vercel.app/reference/methods/) 
如果要查看效果请到文档首页查看[文档](https://earth-flyline-docs.vercel.app)

**Comment by hululuuuuu** [comment]
@paddingH  需求已实现。如果有什么好的想法，可以及时通过 issue 反馈

**Comment by paddingH** [comment]
OK 谢谢，有些自定义内容感觉实际场景挺需要的比如:
1.可以自定义地球旋转的位置
2.可以通过自定义事件方式控制地球的暂停、旋转
3.涟漪效果的位置等

**Comment by hululuuuuu** [comment]
可以参考文档 https://earth-flyline-docs.vercel.app/advance/advance/     自定义视角 间接控制地球旋转的位置
通过修改示例的options属性可以暂停旋转
 myChart.on("click", (event: Event, mesh: any) => {
      myChart.options.autoRotate = false;
    });
    至于涟漪的位置 不太明白意思。
